<?php
$labels = array();
$labels['vacation'] = 'Távollét';
$labels['autoreply'] = 'Automatikus válasz';
$labels['outofoffice'] = 'Távolléti beállítások';
$labels['autoreplysubject'] = 'Automatikus válasz fejléc';
$labels['autoreplymessage'] = 'Automatikus válasz üzenet';
$labels['autoreplybutton'] = 'Mentés';
$labels['mailforward'] = 'Levéltovábbítás';
$labels['separate_alias'] = 'Az egyes továbbítási címeket vesszõvel válaszd el!';
$labels['separate_forward'] = 'Az egyes alternatív címeket vesszõvel válaszd el!';
$labels['keepcopy'] = 'Maradjon másolat a saját postafiókban';
$labels['forwardingaddresses'] = 'Levéltovábbítás ide';
$labels['forward'] = 'Levéltovábbítási beállítások';
$labels['success_changed'] = 'A távolléti és levéltovábbítási beállítások mentése sikerült.';
$labels['failed'] = 'A távolléti és levéltovábbítási beállítások mentése nem sikerült.';
$labels['aliases'] = 'Alternatív címek';
// Button text
$labels['aliasesbutton'] = 'Alternatív címek';
?>
