<?php
$labels = array();
$labels['vacation'] = 'Vacation';
$labels['autoreply'] = 'Attiva notifica vacation';
$labels['outofoffice'] = 'Imposta vacation (out of office)';
$labels['autoreplysubject'] = 'Oggetto della notifica';
$labels['autoreplymessage'] = 'Messaggio automatico';
$labels['autoreplybutton'] = 'Salva';
$labels['mailforward'] = 'Inoltro mail';
$labels['separate_alias'] = 'Separare ogni indirizzo alias con una virgola';
$labels['separate_forward'] = 'Separare ogni indirizzo con una virgola';
$labels['keepcopy'] = 'Mantieni una copia';
$labels['forwardingaddresses'] = 'Inoltra mail a';
$labels['forward'] = 'Impostazioni inoltro';
$labels['success_changed'] = 'Impostazioni vacation salvate correttamente';
$labels['failed'] = 'Errore impostazioni vacation!';
$labels['aliases'] = 'Alias';
// Button text
$labels['aliasesbutton'] = 'Usa identità';
?>