<?php
$labels = array();
$labels['vacation'] = 'Wakacje';
$labels['autoreply'] = "Wyślij powiadomienie";
$labels['outofoffice'] = 'Powiadomienie (Poza Biurem)';
$labels['autoreplysubject'] = 'Temat autoodpowiedzi';
$labels['autoreplymessage'] = 'Treść autoodpowiedzi';
$labels['autoreplybutton'] = 'Zapisz';
$labels['mailforward'] = 'Przekazanie wiadomości';
$labels['separate_alias'] = 'Aliasy oddzielone przecinkiem';
$labels['separate_forward'] = 'Adresy przekazywania oddzielone przecinkiem';
$labels['keepcopy'] = 'Zachowaj kopię wiadomości';
$labels['forwardingaddresses'] = 'Przekaż wiadomość na adres';
$labels['forward'] = 'Ustawienia przekazywania';
$labels['success_changed'] = 'Ustawienia autoodpowiedzi skonfigurowano pomyślnie';
$labels['failed'] = 'Błąd konfiguracji autoodpowiedzi!';
$labels['aliases'] = 'Aliasy';
// Button text
$labels['aliasesbutton'] = 'Pobierz aliasy';
?>
