<?php

//
// sk_SK (utf8) localization for Roundcube Vacation plugin
// works good for acation 1.9.2
// made by Jan.Vajda@somi.sk
//

$labels = array();
$labels['vacation'] = 'Odpovedač';
$labels['autoreply'] = 'Poslať automatickú odpoveď';
$labels['outofoffice'] = 'Automatická odpoveď / Preposielanie';
$labels['autoreplysubject'] = 'Predmet správy';
$labels['autoreplymessage'] = 'Správa';
$labels['autoreplybutton'] = 'Ulož';
$labels['mailforward'] = 'Preposielanie';
$labels['aliases'] = 'Alias';
$labels['keepcopy'] = 'Zachovať kópiu správy v schránke';
$labels['forwardingaddresses'] = 'Presmerovať na';
$labels['forward'] = 'Nastavenie presmerovania';
$labels['success_changed'] = 'Nastavenie bolo úspešne zmenené';
$labels['failed'] = 'Automatickú odpoveď / Preposielanie sa nepodarilo nastaviť!';
$labels['separate_alias'] = 'Viac adries oddeľujte čiarkou';
$labels['separate_forward'] = 'Viac adries pre presmerovanie oddeľujte čiarkou';
$labels['aliasesbutton'] = 'Získať aliasy';
?>
