<?php
$labels = array();
$labels['vacation'] = '休假';
$labels['autoreply'] = "發出通知";
$labels['outofoffice'] = '休假 (走出辦公室) 通知';
$labels['autoreplysubject'] = '自動回應的主題';
$labels['autoreplymessage'] = '自動回應的內容';
$labels['autoreplybutton'] = '儲存';
$labels['mailforward'] = '郵件轉送';
$labels['separate_alias'] = '以逗點分隔開每一個假名';
$labels['separate_forward'] = '以逗點分隔開每一個轉送郵址';
$labels['keepcopy'] = '保存一份郵件副本';
$labels['forwardingaddresses'] = '轉送郵件到';
$labels['forward'] = '郵件轉送設定';
$labels['success_changed'] = '休假設定更換成功';
$labels['failed'] = '休假設定更換失敗!';
$labels['aliases'] = '假名';
// Button text
$labels['aliasesbutton'] = '取得假名';
?>
