## mysqldiff 0.43
## 
## Run on Wed Feb  1 20:22:51 2012
## Options: debug=0
##
## --- file: doc/vboxadm/mysql/vboxadm-current.sql
## +++ file: /tmp/ee91R6gisM/vboxadm-current.sql

ALTER TABLE aliases ENGINE=InnoDB DEFAULT CHARSET=utf8; # was ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8
ALTER TABLE awl ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
ALTER TABLE domain_aliases ENGINE=InnoDB DEFAULT CHARSET=latin1; # was ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1
ALTER TABLE domains ENGINE=InnoDB DEFAULT CHARSET=latin1; # was ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1
ALTER TABLE mailboxes ENGINE=InnoDB DEFAULT CHARSET=latin1; # was ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1
ALTER TABLE rfc_notify ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
ALTER TABLE role_accounts ENGINE=MyISAM DEFAULT CHARSET=utf8; # was ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
ALTER TABLE vacation_blacklist ENGINE=InnoDB DEFAULT CHARSET=utf8; # was ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
